import Head from 'next/head';
import Nav from './components/Nav';
import Hero from './components/Hero';
import About from './components/About';
import Pricing from './components/Pricing';
import Contact from './components/Contact';
import Footer from './components/Footer';
import Photos from './components/Photos';

const Home = () => {
  return (
    <div>

      <Head>
        <title>QCM-Detailing</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>

        <section id="home" className='relative grow bg-primary bg-cover bg-center' style={{backgroundImage: "url('/herobg.jpg')"}} >
          <Nav sections={['home', 'about', 'booking', 'contact']}/>
          <Hero />   
        </section>

        <section id="about">
          <About/>
        </section>

        {/* <section id="photos">
          <Photos/>
        </section> */}

        <section id="pricing">
          <Pricing/>
        </section>

        <section id="contact">
          <h1 className='text-6xl font-semibold text-center p-6'>Booking</h1>
          <p className='p-5 text-2xl text-center md:text-3xl pb-5'>Please fill in both forms correctly to get your Quote as soon as possible</p>
          <Contact/>
        </section>
  
        <section>
          <Footer/>
        </section>

      </main>

    </div>
  );
};




export default Home;
